# Generated by Django 2.0 on 2017-12-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.IntegerField(help_text='compiler id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='compiler nam', max_length=128)),
                ('ver', models.CharField(help_text='compiler version', max_length=128)),
                ('short', models.CharField(help_text='short name', max_length=128)),
                ('ace', models.CharField(help_text='syntax highlighting identifier for Ace', max_length=128)),
                ('geshi', models.CharField(help_text='syntax highlighting identifier for Geshi', max_length=128)),
                ('pygments', models.CharField(help_text='syntax highlighting identifier for Pygments', max_length=128)),
                ('highlighting', models.CharField(help_text='syntax highlighting identifier for Highlighting', max_length=128)),
                ('rouge', models.CharField(help_text='syntax highlighting identifier for Rouge', max_length=128)),
                ('codemirror', models.CharField(help_text='syntax highlighting identifier for CodeMirror', max_length=128)),
            ],
        ),
    ]
