# Generated by Django 2.0 on 2017-12-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compiler',
            name='highlighting',
        ),
        migrations.AddField(
            model_name='compiler',
            name='highlights',
            field=models.CharField(default='', help_text='syntax highlighting identifier for Highlights', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compiler',
            name='id',
            field=models.IntegerField(help_text='compiler id', primary_key=True, serialize=False, verbose_name='Compiler ID'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='name',
            field=models.CharField(help_text='compiler name', max_length=128, verbose_name='Compiler Name'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='short',
            field=models.CharField(help_text='short name', max_length=128, verbose_name='Compiler Short Name'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='ver',
            field=models.CharField(help_text='compiler version', max_length=128, verbose_name='Compiler Version'),
        ),
    ]
