# Generated by Django 2.0 on 2017-12-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171224_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.IntegerField(help_text='submission id', primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('ti', models.FloatField(help_text='execution time in seconds', verbose_name='Execution Time')),
                ('memory', models.IntegerField(help_text='memory consumed by the program in kilobytes', verbose_name='Memory Consumed')),
            ],
        ),
        migrations.AlterModelOptions(
            name='compiler',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='compiler',
            name='ace',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Ace', max_length=128),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='codemirror',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for CodeMirror', max_length=128),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='geshi',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Geshi', max_length=128),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='highlights',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Highlights', max_length=128),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='pygments',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Pygments', max_length=128),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='rouge',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Rouge', max_length=128),
        ),
    ]
