# Generated by Django 2.0 on 2017-12-24 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171224_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='reation date and time (on server); format: yyyy-mm-\xaddd hh:mm:ss; eg. 2009\xad-05-\xad19 02:\xad34:\xad56', verbose_name='Creation DateTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Finished'), (1, 'Compilation'), (3, 'Running'), (None, 'Waiting For Compilation')], default=9, help_text='current status; see section "Status and result"', verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compiler',
            name='id',
            field=models.IntegerField(help_text='compiler id', primary_key=True, serialize=False, verbose_name='Compiler ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.IntegerField(help_text='submission id', primary_key=True, serialize=False, verbose_name='Submission ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(help_text='memory consumed by the program in kilobytes', verbose_name='Memory Consumed'),
        ),
    ]
