# Generated by Django 2.0 on 2017-12-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171224_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='result',
            field=models.IntegerField(choices=[(11, 'Compilation Error'), (12, 'Runtime Error'), (13, 'Time Limit Exceeded'), (15, 'Success'), (17, 'Memory Limit Exceeded'), (19, 'Illegal System Call'), (20, 'Internal Error')], default=1, help_text='current result; see section "Status and result"', verbose_name='Result'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Finished'), (1, 'Compilation'), (3, 'Running'), (-1, 'Waiting For Compilation')], help_text='current status; see section "Status and result"', verbose_name='Status'),
        ),
    ]
