# Generated by Django 2.0 on 2017-12-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171224_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compiler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Compiler', to= 'core.Language', verbose_name= 'Compiler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='signal',
            field=models.IntegerField(default=0, help_text='signal raised by the program', verbose_name='Signal'),
            preserve_default=False,
        ),
    ]
