# Generated by Django 2.0 on 2017-12-24 00:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171224_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(help_text='execution time in seconds', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Execution Time')),
                ('memory', models.IntegerField(help_text='memory consumed by the program in kilobytes', verbose_name='Memory Consumed')),
                ('date', models.DateTimeField(help_text='reation date and time (on server); format: yyyy-mm-\xaddd hh:mm:ss; eg. 2009\xad-05-\xad19 02:\xad34:\xad56', verbose_name='Creation DateTime')),
                ('status', models.IntegerField(choices=[(0, 'Finished'), (1, 'Compilation'), (3, 'Running'), (-1, 'Waiting For Compilation')], help_text='current status; see section "Status and result"', verbose_name='Status')),
                ('result', models.IntegerField(choices=[(11, 'Compilation Error'), (12, 'Runtime Error'), (13, 'Time Limit Exceeded'), (15, 'Success'), (17, 'Memory Limit Exceeded'), (19, 'Illegal System Call'), (20, 'Internal Error')], help_text='current result; see section "Status and result"', verbose_name='Result')),
                ('signal', models.IntegerField(help_text='signal raised by the program', verbose_name='Signal')),
                ('compiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to= 'core.Language', verbose_name= 'Compiler')),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='result',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time',
        ),
        migrations.AddField(
            model_name='submission',
            name='input',
            field=models.TextField(blank=True, help_text='data that will be provided to the program as stdin stream, default: empty', null=True, verbose_name='Input'),
        ),
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.TextField(blank=True, help_text='source code to run, default: empty', null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='compiler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=
            'core.Language'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.IntegerField(help_text='id of created submission', primary_key=True, serialize=False, verbose_name='Submission ID'),
        ),
        migrations.AddField(
            model_name='submissioninfo',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Submission'),
        ),
    ]
