# Generated by Django 2.0 on 2017-12-24 00:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171224_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissioninfo',
            name='compiler',
        ),
        migrations.RemoveField(
            model_name='submissioninfo',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='reation date and time (on server); format: yyyy-mm-\xaddd hh:mm:ss; eg. 2009\xad-05-\xad19 02:\xad34:\xad56', verbose_name='Creation DateTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=1, help_text='memory consumed by the program in kilobytes', verbose_name='Memory Consumed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='result',
            field=models.IntegerField(choices=[(11, 'Compilation Error'), (12, 'Runtime Error'), (13, 'Time Limit Exceeded'), (15, 'Success'), (17, 'Memory Limit Exceeded'), (19, 'Illegal System Call'), (20, 'Internal Error')], default=1, help_text='current result; see section "Status and result"', verbose_name='Result'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='signal',
            field=models.IntegerField(default=1, help_text='signal raised by the program', verbose_name='Signal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Finished'), (1, 'Compilation'), (3, 'Running'), (-1, 'Waiting For Compilation')], default=1, help_text='current status; see section "Status and result"', verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.FloatField(default=1, help_text='execution time in seconds', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Execution Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='compiler',
            field=models.ForeignKey(default=1, help_text='compiler identifier, default: 1 (C++)', on_delete=django.db.models.deletion.CASCADE, to= 'core.Language'),
        ),
        migrations.DeleteModel(
            name='SubmissionInfo',
        ),
    ]
