# Generated by Django 2.0 on 2017-12-24 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171224_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=6, unique=True, verbose_name='Code')),
                ('source', models.TextField(help_text='last source editted', verbose_name='Source')),
                ('input', models.TextField(verbose_name='Input')),
                ('output', models.TextField(verbose_name='Output')),
            ],
        ),
        migrations.AlterField(
            model_name='compiler',
            name='ace',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Ace', max_length=128, verbose_name='Ace'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='codemirror',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for CodeMirror', max_length=128, verbose_name='CodeMirror'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='geshi',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Geshi', max_length=128, verbose_name='Geshi'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='highlights',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Highlights', max_length=128, verbose_name='Highlights'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='pygments',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Pygments', max_length=128, verbose_name='Pygments'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='rouge',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Rouge', max_length=128, verbose_name='Rouge'),
        ),
        migrations.AddField(
            model_name='code',
            name='compiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compiler'),
        ),
    ]
