# Generated by Django 2.0 on 2017-12-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171224_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='compiler',
        ),
        migrations.RemoveField(
            model_name='code',
            name='input',
        ),
        migrations.RemoveField(
            model_name='code',
            name='output',
        ),
        migrations.AddField(
            model_name='code',
            name='last_submission',
            field=models.ForeignKey(blank=True, help_text='last submission of this code/note', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.SlugField(help_text='url identifier for this code, default = <random>', max_length=6, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='code',
            name='source',
            field=models.TextField(help_text='last captured version of this code/note', verbose_name='Source'),
        ),
    ]
