# Generated by Django 2.0 on 2017-12-24 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20171224_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='the user logged in at the time this code/note created', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner/Creator'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.SlugField(help_text='url identifier for this code, randomly generated by default', max_length=6, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='code',
            name='last_submission',
            field=models.ForeignKey(blank=True, help_text='last submission of this code/note', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='compiler',
            field=models.ForeignKey(blank=True, default=1, help_text='compiler identifier, default: 1 (C++)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Compiler'),
        ),
    ]
