# Generated by Django 2.0 on 2018-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171224_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='code',
        ),
        migrations.AddField(
            model_name='code',
            name='uri',
            field=models.SlugField(default=1, help_text='uri identifier for this code, randomly generated by default', max_length=64, unique=True, verbose_name='URI'),
            preserve_default=False,
        ),
    ]
