# Generated by Django 2.0 on 2018-02-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180206_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='password',
            field=models.CharField(default='password', help_text='password, if any', max_length=128, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='version',
            field=models.IntegerField(default=0, help_text='version counter', verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='code',
            name='last_submission',
            field=models.ForeignKey(blank=True, help_text='last code submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='code',
            name='source',
            field=models.TextField(help_text='last captured version', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(help_text='creation date and time (on server);\nformat: yyyy-mm-\xaddd hh:mm:ss; eg. 2009\xad-05-\xad19 02:\xad34:\xad56', verbose_name='Creation DateTime'),
        ),
    ]
