# Generated by Django 2.0 on 2018-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180207_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='uri',
            field=models.SlugField(help_text='uri identifier for this code, randomly generated if not set', max_length=64, unique=True, verbose_name='URI'),
        ),
    ]
