# Generated by Django 2.0 on 2018-02-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180207_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='password',
            field=models.CharField(blank=True, help_text='password, if any', max_length=128, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='code',
            name='source',
            field=models.TextField(blank=True, help_text='last captured version', null=True, verbose_name='Source'),
        ),
    ]
