# Generated by Django 2.0 on 2018-02-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180209_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='source',
            field=models.TextField(blank=True, default='', help_text='last captured version', null=True, verbose_name='Source'),
        ),
    ]
