# Generated by Django 2.0 on 2018-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180209_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='mime',
            field=models.CharField(blank=True, help_text='file MIME type', max_length=128, null=True, verbose_name='MIME'),
        ),
        migrations.AlterField(
            model_name='code',
            name='uri',
            field=models.SlugField(help_text='URI identifier for this code, randomly generated if not set', max_length=64, unique=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='ace',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Ace', max_length=128, null=True, verbose_name='Ace'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='codemirror',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for CodeMirror', max_length=128, null=True, verbose_name='CodeMirror'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='geshi',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Geshi', max_length=128, null=True, verbose_name='Geshi'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='highlights',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Highlights', max_length=128, null=True, verbose_name='Highlights'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='pygments',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Pygments', max_length=128, null=True, verbose_name='Pygments'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='rouge',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for Rouge', max_length=128, null=True, verbose_name='Rouge'),
        ),
    ]
