# Generated by Django 2.0 on 2018-03-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180319_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='short',
            field=models.CharField(blank=True, help_text='short name', max_length=128, null=True, verbose_name='Compiler Short Name'),
        ),
    ]
