# Generated by Django 2.0 on 2018-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180319_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='highlightjs',
            field=models.CharField(blank=True, help_text='syntax highlighting identifier for highlight.js', max_length=128, null=True, verbose_name='CodeMirror'),
        ),
    ]
