# Generated by Django 2.0 on 2018-03-22 12:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180322_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='uri',
            field=models.CharField(help_text='URI identifier for this code, randomly generated if not set', max_length=64, unique=True, validators=[core.models.validate_alphanumeric], verbose_name='URI'),
        ),
    ]
