# Generated by Django 2.0 on 2018-03-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180322_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='compiler',
            new_name='language',
        ),
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.ForeignKey(blank=True, help_text='latest language associated to this code', null=True, on_delete=django.db.models.deletion.SET_NULL, to= 'core.Language'),
        ),
        migrations.AlterField(
            model_name='code',
            name='last_submission',
            field=models.ForeignKey(blank=True, help_text='latest code submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Submission'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='id',
            field=models.IntegerField(help_text='language id', primary_key=True, serialize=False, verbose_name='Language ID'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='name',
            field=models.CharField(help_text='language name', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='short',
            field=models.CharField(blank=True, help_text='short name', max_length=128, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='ver',
            field=models.CharField(help_text='language version', max_length=128, verbose_name='Version'),
        ),
    ]
