# Generated by Django 2.0 on 2018-03-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_manual_20180325_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(blank=True, default=1, help_text='language identifier, default: 1 (C++)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Language'),
        ),
    ]
