# Generated by Django 2.0 on 2018-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180325_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='password',
            field=models.CharField(blank=True, editable=False, help_text='password, if any', max_length=128, null=True, verbose_name='Password'),
        ),
    ]
